headerTextFormat = new TextFormat();
headerTextFormat.font = "Cooper Black";
headerTextFormat.color = 16777215;
headerTextFormat.size = 24;
headerTextFormat.align = "left";
this.createTextField("headerText",3,-244,-50,400,22);
headerText.embedFonts = true;
headerText.wordWrap = false;
headerText.selectable = false;
headerText.text = _global.AwardTrait(_global.InspectingAward,"Title");
headerText.setTextFormat(headerTextFormat);
dataTextFormat = new TextFormat();
dataTextFormat.font = "Cooper Black";
dataTextFormat.color = 16777215;
dataTextFormat.size = 12;
dataTextFormat.align = "left";
this.createTextField("dataText",1,-237,-22,480,65);
dataText.embedFonts = true;
dataText.wordWrap = true;
dataText.selectable = false;
dataText.text = _global.AwardTrait(_global.InspectingAward,"Description");
dataText.setTextFormat(dataTextFormat);
dataText._width -= 1;
stop();
